# markdownlint - style checker and lint tool for Markdown/CommonMark files.
# https://github.com/DavidAnson/markdownlint#rules--aliases

MD013:
  line_length: 120
MD026: false
MD033: false
MD034: false
MD041: false
MD046:
  style: fenced
