sudo: false # route the build to a container-based infrastructure for faster builds
language: ruby
cache: bundler # cache bundle between builds to drastically build runtime.

# The lowest supported version of ruby is mapped to GitHub Pages dependency.
# https://pages.github.com/versions/
rvm:
  - 2.4
  - ruby-head

# Install all bundle dependencies, and then run the verifiers
install:
  - travis_retry bundle install
before_script:
  - bundle exec jekyll --version
script:
  - make verifiers

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# Define rows that are allowed to fail without causing the entire build to fail.
# This allows us to add in experimental and preparatory builds to test against
# versions and configurations that we're not ready to officially support.
matrix:
  allow_failures:
  - rvm: ruby-head
