locale: en-US
title: syntaqx

github: [metadata]
repository: syntaqx/syntaqx.github.io

analytics:
  google: UA-141192690-1

twitter:
  username: syntaqx
facebook:
  username:
  app_id:
  publisher:
og_image: /assets/img/og-fallback.png
social:
  type: Person
  name: Chase Pierce
  links:
    - https://keybase.io/syntaqx
    - https://twitter.com/syntaqx
    - https://www.linkedin.com/in/syntaqx/
    - https://github.com/syntaqx

webmaster_verifications:
  google: 196131356

collections:
  components:
    output: true
    permalink: /components/:path/
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
    values:
      layout: default
      image: /assets/img/og-fallback.png
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page

exclude:
  - Gemfile*
  - README.md

# Plugins which are activated
plugins:
- jekyll-coffeescript
- jekyll-commonmark-ghpages
- jekyll-gist
- jekyll-github-metadata
- jekyll-paginate
- jekyll-seo-tag
- jekyll-relative-links
- jekyll-optional-front-matter
- jekyll-readme-index
- jekyll-default-layout
- jekyll-titles-from-headings

# Plugins allowed by GitHub Pages
whitelist:
- jekyll-coffeescript
- jekyll-commonmark-ghpages
- jekyll-feed
- jekyll-gist
- jekyll-github-metadata
- jekyll-paginate
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-avatar
- jemoji
- jekyll-mentions
- jekyll-relative-links
- jekyll-optional-front-matter
- jekyll-readme-index
- jekyll-default-layout
- jekyll-titles-from-headings
- jekyll-include-cache
- jekyll-octicons
- jekyll-remote-theme

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
