# Configuration settings that affect the entire site. These values are generally
# expected to be set up once, and rarely changed after that.
#
# For technical reasons, this file is *NOT* reloaded automatically when using
# `jekyll serve`. If you make changes to this file, you will need to restart the
# local server.

# Project settings
name: &name syntaqx
title: *name
copyright: *name
description: null
email: syntaqx@gmail.com
locale: en-US

# url settings
baseurl: ""                # the subpath of your site, e.g. /blog
url: "https://syntaqx.com" # baseline & protocol of the site, without trailing slash

# Default site author
author: chase

# Social profile links
# https://developers.google.com/structured-data/customize/social-profiles
social:
  type: "Person" # must be either: Person or Organization (defaults to Person)
  name: "Chase Hutchins"
  links:
    - "https://github.com/syntaqx"
    - "https://twitter.com/syntaqx"
    - "https://plus.google.com/+ChaseHutchins"
    - "https://www.youtube.com/user/syntaqx"
    - "https://www.linkedin.com/in/syntaqx"

# Analytics
analytics:
  google:
    type: "google" # must be either: google or universal (defaults to google)
    tracking_id: ""

# Site verification codes
site_verification:
  google: ""
  bing: ""
  alexa: ""
  yandex: ""

# Project rendering settings
title_separator: "-"
date_format: "%b %-d, %Y"

# Outputting
permalink: /blog/:categories/:title
paginate: 5
paginate_path: "blog/page:num"
timezone: UTC # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Handling Reading
include: ["_pages"]

# Collections
collections:
  products:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page

# Plugins (previously gems)
# You can mimic GitHub Pages with --safe
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

# HTML compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: [local, development]

# Feed
feed:
  path: atom.xml
