# Configuration settings that affect the entire site. These values are generally
# expected to be set up once, and rarely changed after that.
#
# For technical reasons, this file is *NOT* reloaded automatically when using
# `jekyll serve`. If you make changes to this file, you will need to restart the
# local server.

# Project settings
title: &title syntaqx
description: null
lang: "en-US"

# Compatibility named variables
# These exist to provide consistency with expectations from plugins.
name: *title

# Date settings
date_format: "%b %-d, %Y"

# url settings
baseurl: ""                # the subpath of your site, e.g. /blog
url: "https://syntaqx.com" # baseline & protocol of the site, without trailing slash
repository: "syntaqx/syntaqx.github.io"

# Default site author
author: chase

# Social profile links
# https://developers.google.com/structured-data/customize/social-profiles
social:
  type: "Person" # must be either: Person or Organization (defaults to Person)
  name: "Chase Hutchins"
  links:
    - "https://github.com/syntaqx"
    - "https://twitter.com/syntaqx"
    - "https://plus.google.com/+ChaseHutchins"
    - "https://www.youtube.com/user/syntaqx"
    - "https://www.linkedin.com/in/syntaqx"

# Analytics
analytics:
  google:
    type: "google" # must be either: google or universal (defaults to google)
    tracking_id: "UA-48212212-1"

# Site verification codes
site_verification:
  google: ""
  bing: ""
  alexa: ""
  yandex: ""

# Project rendering settings
title_separator: "-"

# Conversion
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Outputting
permalink: /blog/:categories/:title
paginate: 5
paginate_path: "/blog/page:num/"
timezone: UTC # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Handling Reading
include: ["_pages"]

# Collections
collections:

# Defaults
defaults:
  # *
  - scope:
      path: ""
    values:
      lang: en
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: page

# Plugins (previously gems)
plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

# HTML compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: [local, development]

# Feed
feed:
  path: atom.xml
