# jekyll configuration
# ------------------------------------------------------------------------------

pygments:  true
permalink: /posts/:title/
exclude:   ['README.md', 'components/font-awesome/src']
markdown:  rdiscount
rdiscount:
    extension: [smart]

# meta information
title: syntaqx
url:   http://syntaqx.com
author:
    name: Chase Hutchins
    email: syntaqx@gmail.com
twitter: syntaqx
github: syntaqx