version: 2.1
jobs:
  generate_ips:
    docker:
      - image: syntaqx/dnsutils
    environment:
      DOMAIN: syntaqx.mynetgear.com
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["a6:c2:89:37:50:ad:0b:0f:b7:3d:8a:95:6a:0e:8a:94"]
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: |
          git config user.email "circleci@syntaqx.com"
          git config user.name "CircleCI Generator"
      - run: |
          chmod +x ./scripts/generate_ips.sh
          ./scripts/generate_ips.sh
      - run: |
          git commit -am 'Automated deployment from CircleCI [skip ci]'
          git push -q

workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                - beta
    jobs:
      - generate_ips
