version: 2.1
jobs:
  generate_ips:
    docker:
      - image: syntaqx/dnsutils
    environment:
      DOMAIN: syntaqx.mynetgear.com
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["19:19:21:4e:7f:fb:d4:7d:97:92:95:40:c9:a1:f0:5c"]
      - run: ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      - run:
          name: Configure Git client
          command: |
            git config user.email "build@circleci.com"
            git config user.name "Automated CircleCI Build"
      - run:
          name: Generate & update IP list
          command: |
            chmod +x ./scripts/generate_ips.sh
            ./scripts/generate_ips.sh
      - run:
          name: Git commit and push
          command: |
            git commit -am 'Automated deployment from CircleCI [skip ci]'
            git push -q

workflows:
  version: 2
  commit:
    jobs:
      - generate_ips
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - generate_ips
